/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory;
import Consumable.Consumable;
import Consumable.ConsumableManager;
import Equipment.EquipmentManager;
import Equipment.Equipment;
import Report.ReportFactory;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Point;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utils.StaticDate;

/**
 *
 * @author Jovani
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
   private static int index; 
   
   
   public Home(int Index)
   {
       this.index = Index;
   }
   
    public Home() {
        
        initComponents();
        
        if (index == 1)
        {
            jTabbedPane1.setEnabledAt(1, false);
            
            if (jTabbedPane1.getSelectedIndex() == 1)
                jTabbedPane1.setSelectedIndex(0);
               
               try
               {     
                EquipmentManager.showTable(jTable1);
               }
               catch(SQLException e){}
                   
        }
        else if (index == -1)
        {
            jTabbedPane1.setEnabledAt(0, false);
            
           if (jTabbedPane1.getSelectedIndex() == 0)
                jTabbedPane1.setSelectedIndex(1);
           
                 try
               {     
                ConsumableManager.showTable(jTable2_Consumable);
               }
               catch(SQLException e){}
        }
        else if (index == 0) 
        {
             try
               {     
                EquipmentManager.showTable(jTable1);
               }
               catch(SQLException e){}
            
            jbuttonAdd.setEnabled(false);
            jButtonUpdate.setEnabled(false);
            jButton2.setEnabled(false);
        }
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 20));
        jTable1.setRowHeight(30);
        
        
        jTable2_Consumable.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable2_Consumable.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 15));
        jTable2_Consumable.setRowHeight(30);
         
        
        setResizable(true);
        setVisible(true);
        
    }
    
    
    public void setLoggedInUser(String User)
    {
        LoggedInUser.setText(User);
        LoggedInUser1.setText(User);
    }
    
      
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        EquipmentInfo = new javax.swing.JPanel();
        Manufacturer = new javax.swing.JLabel();
        ModelComputer = new javax.swing.JLabel();
        jModelComputerT = new javax.swing.JTextField();
        ServiceTag = new javax.swing.JLabel();
        jServiceTagT = new javax.swing.JTextField();
        Memory = new javax.swing.JLabel();
        jHardDriveT = new javax.swing.JTextField();
        HardDrive = new javax.swing.JLabel();
        Location = new javax.swing.JLabel();
        jComboBoxLocation = new javax.swing.JComboBox<>();
        jManufacturerT = new javax.swing.JTextField();
        UserID = new javax.swing.JLabel();
        jUserIdT = new javax.swing.JTextField();
        UsersName = new javax.swing.JLabel();
        HostName = new javax.swing.JLabel();
        jHostNameT = new javax.swing.JTextField();
        UWIAssetTAG = new javax.swing.JLabel();
        jUWIAssestTagT = new javax.swing.JTextField();
        ShippedDate = new javax.swing.JLabel();
        WarrantyEndDate = new javax.swing.JLabel();
        jUSERSNameT = new javax.swing.JTextField();
        jMemoryT = new javax.swing.JTextField();
        jDateChooserShippedDate = new com.toedter.calendar.JDateChooser();
        jDateChooserWarrantyDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LoggedInUser = new javax.swing.JLabel();
        SignOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jbuttonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButton1_GenReportEquipment = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        EquipmentInfo1 = new javax.swing.JPanel();
        jNameConsumableL = new javax.swing.JLabel();
        jManufacturerConsumableL = new javax.swing.JLabel();
        jManufacturerConsumableT = new javax.swing.JTextField();
        jQuantityConsumableL = new javax.swing.JLabel();
        jQuantityConsumableT = new javax.swing.JTextField();
        jSizeConsumableL = new javax.swing.JLabel();
        jLocationConsumableL = new javax.swing.JLabel();
        jLocationConsumableT = new javax.swing.JTextField();
        jTypeConsumableL = new javax.swing.JLabel();
        jNameConsumableT = new javax.swing.JTextField();
        jExpDateConsumableL = new javax.swing.JLabel();
        jTypeConsumableT = new javax.swing.JTextField();
        jSizeConsumableT = new javax.swing.JTextField();
        jDateChooserExpDateConsumable = new com.toedter.calendar.JDateChooser();
        jPanel18 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        LoggedInUser1 = new javax.swing.JLabel();
        SignOut1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel19 = new javax.swing.JPanel();
        jButtonRemove3_Consumable = new javax.swing.JButton();
        jbuttonAdd1_Consumable = new javax.swing.JButton();
        jButtonUpdate1_Consumable = new javax.swing.JButton();
        JButton1_GenReport_Consumable = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2_Consumable = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuRegister = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        EquipmentInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Equipment Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17), new java.awt.Color(51, 102, 255))); // NOI18N

        Manufacturer.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Manufacturer.setText("Manufacturer");

        ModelComputer.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        ModelComputer.setText("Model Computer");

        jModelComputerT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        ServiceTag.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        ServiceTag.setText("Service TAG");

        jServiceTagT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        Memory.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Memory.setText("Memory");

        jHardDriveT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        HardDrive.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        HardDrive.setText("Hard Drive");

        Location.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        Location.setText("Location");

        jComboBoxLocation.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        jComboBoxLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T.M.R.U", "E.R.U", "S.C.U" }));

        jManufacturerT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        UserID.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        UserID.setText("USER ID");

        jUserIdT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        UsersName.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        UsersName.setText("USERS Name");

        HostName.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        HostName.setText("Host Name");

        jHostNameT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        UWIAssetTAG.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        UWIAssetTAG.setText("UWI Asset TAG");

        jUWIAssestTagT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        ShippedDate.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        ShippedDate.setText("Shipped Date");

        WarrantyEndDate.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        WarrantyEndDate.setText("Warranty End Date");

        jUSERSNameT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jMemoryT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jDateChooserShippedDate.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jDateChooserWarrantyDate.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        javax.swing.GroupLayout EquipmentInfoLayout = new javax.swing.GroupLayout(EquipmentInfo);
        EquipmentInfo.setLayout(EquipmentInfoLayout);
        EquipmentInfoLayout.setHorizontalGroup(
            EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquipmentInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Manufacturer)
                    .addComponent(ModelComputer)
                    .addComponent(ServiceTag)
                    .addComponent(Memory)
                    .addComponent(HardDrive)
                    .addComponent(Location))
                .addGap(35, 35, 35)
                .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHardDriveT)
                    .addComponent(jComboBoxLocation, 0, 213, Short.MAX_VALUE)
                    .addComponent(jServiceTagT)
                    .addComponent(jMemoryT)
                    .addComponent(jModelComputerT)
                    .addComponent(jManufacturerT))
                .addGap(53, 53, 53)
                .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EquipmentInfoLayout.createSequentialGroup()
                        .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ShippedDate)
                            .addComponent(WarrantyEndDate))
                        .addGap(76, 76, 76)
                        .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooserShippedDate, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jDateChooserWarrantyDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(EquipmentInfoLayout.createSequentialGroup()
                        .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserID)
                            .addComponent(UsersName)
                            .addComponent(HostName)
                            .addComponent(UWIAssetTAG))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jUSERSNameT, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jHostNameT)
                            .addComponent(jUserIdT, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jUWIAssestTagT))))
                .addContainerGap())
        );
        EquipmentInfoLayout.setVerticalGroup(
            EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquipmentInfoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Manufacturer)
                    .addComponent(jManufacturerT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUSERSNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsersName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModelComputer)
                    .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jModelComputerT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserID)
                        .addComponent(jUserIdT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHostNameT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jServiceTagT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ServiceTag))
                    .addComponent(HostName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUWIAssestTagT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UWIAssetTAG)
                    .addComponent(Memory)
                    .addComponent(jMemoryT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EquipmentInfoLayout.createSequentialGroup()
                        .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HardDrive)
                            .addComponent(jHardDriveT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ShippedDate))
                        .addGap(18, 18, 18)
                        .addComponent(Location)
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(EquipmentInfoLayout.createSequentialGroup()
                        .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(EquipmentInfoLayout.createSequentialGroup()
                                .addComponent(jDateChooserShippedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jDateChooserWarrantyDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EquipmentInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WarrantyEndDate)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel1.setText("Welcome");

        LoggedInUser.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        LoggedInUser.setText("jLabel3");

        SignOut.setText("Sign Out");
        SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel3.setText("User Role");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(59, 59, 59)
                                .addComponent(LoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(SignOut)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoggedInUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignOut)
                .addGap(7, 7, 7))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controllers", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17), new java.awt.Color(51, 102, 255)))); // NOI18N
        jPanel14.setPreferredSize(new java.awt.Dimension(313, 382));
        jPanel14.setRequestFocusEnabled(false);

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbuttonAdd.setText("Add Item");
        jbuttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAddActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.setMaximumSize(new java.awt.Dimension(77, 29));
        jButtonUpdate.setMinimumSize(new java.awt.Dimension(77, 29));
        jButtonUpdate.setPreferredSize(new java.awt.Dimension(77, 29));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButton1_GenReportEquipment.setText("Generate Report");
        jButton1_GenReportEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_GenReportEquipmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1_GenReportEquipment)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(jbuttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(60, 60, 60))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jbuttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1_GenReportEquipment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EquipmentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EquipmentInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Equipment Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17), new java.awt.Color(0, 102, 255)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17))); // NOI18N

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Manufacturer", "Model Computer", "Service TAG", "Memory", "Hard Drive", "Location", "Shipped Date", "Warranty End Date", "User ID", "UsersName", "UWI Asset TAG", "Host Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setText("Search Service TAG");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel5.setText("Search Manufacturer");

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(721, 721, 721))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1869, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("CAIHR MAIN LIST", jPanel6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Equipment Inventory", jPanel1);

        EquipmentInfo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consumable Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17), new java.awt.Color(51, 102, 255))); // NOI18N

        jNameConsumableL.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jNameConsumableL.setText("Name");

        jManufacturerConsumableL.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jManufacturerConsumableL.setText("Manufacturer");

        jManufacturerConsumableT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jQuantityConsumableL.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jQuantityConsumableL.setText("Quantity");

        jQuantityConsumableT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jSizeConsumableL.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jSizeConsumableL.setText("Size");

        jLocationConsumableL.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLocationConsumableL.setText("Location");

        jLocationConsumableT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jTypeConsumableL.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTypeConsumableL.setText("Type");

        jNameConsumableT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jExpDateConsumableL.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jExpDateConsumableL.setText("Exp Date");

        jTypeConsumableT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jSizeConsumableT.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        jDateChooserExpDateConsumable.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        javax.swing.GroupLayout EquipmentInfo1Layout = new javax.swing.GroupLayout(EquipmentInfo1);
        EquipmentInfo1.setLayout(EquipmentInfo1Layout);
        EquipmentInfo1Layout.setHorizontalGroup(
            EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquipmentInfo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNameConsumableL)
                    .addComponent(jManufacturerConsumableL)
                    .addComponent(jQuantityConsumableL)
                    .addComponent(jSizeConsumableL))
                .addGap(35, 35, 35)
                .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jQuantityConsumableT, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jSizeConsumableT)
                    .addComponent(jManufacturerConsumableT)
                    .addComponent(jNameConsumableT))
                .addGap(53, 53, 53)
                .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EquipmentInfo1Layout.createSequentialGroup()
                        .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLocationConsumableL)
                            .addComponent(jTypeConsumableL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTypeConsumableT, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jLocationConsumableT, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(EquipmentInfo1Layout.createSequentialGroup()
                        .addComponent(jExpDateConsumableL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(jDateChooserExpDateConsumable, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        EquipmentInfo1Layout.setVerticalGroup(
            EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EquipmentInfo1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNameConsumableL)
                    .addComponent(jNameConsumableT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTypeConsumableT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTypeConsumableL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jManufacturerConsumableL)
                    .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jManufacturerConsumableT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLocationConsumableL)
                        .addComponent(jLocationConsumableT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserExpDateConsumable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jQuantityConsumableT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jQuantityConsumableL)
                        .addComponent(jExpDateConsumableL)))
                .addGap(28, 28, 28)
                .addGroup(EquipmentInfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSizeConsumableT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSizeConsumableL))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Info", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel6.setText("Welcome");

        LoggedInUser1.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        LoggedInUser1.setText("jLabel3");

        SignOut1.setText("Sign Out");
        SignOut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOut1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel7.setText("User Role");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(59, 59, 59)
                                .addComponent(LoggedInUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(SignOut1)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoggedInUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SignOut1)
                .addGap(7, 7, 7))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controllers", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17), new java.awt.Color(51, 102, 255)))); // NOI18N
        jPanel19.setPreferredSize(new java.awt.Dimension(313, 382));
        jPanel19.setRequestFocusEnabled(false);

        jButtonRemove3_Consumable.setText("Remove");
        jButtonRemove3_Consumable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemove3_ConsumableActionPerformed(evt);
            }
        });

        jbuttonAdd1_Consumable.setText("Add Item");
        jbuttonAdd1_Consumable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonAdd1_ConsumableActionPerformed(evt);
            }
        });

        jButtonUpdate1_Consumable.setText("Update");
        jButtonUpdate1_Consumable.setMaximumSize(new java.awt.Dimension(77, 29));
        jButtonUpdate1_Consumable.setMinimumSize(new java.awt.Dimension(77, 29));
        jButtonUpdate1_Consumable.setPreferredSize(new java.awt.Dimension(77, 29));
        jButtonUpdate1_Consumable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdate1_ConsumableActionPerformed(evt);
            }
        });

        JButton1_GenReport_Consumable.setText("Generate Report");
        JButton1_GenReport_Consumable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton1_GenReport_ConsumableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButton1_GenReport_Consumable)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonRemove3_Consumable, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(jbuttonAdd1_Consumable, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addComponent(jButtonUpdate1_Consumable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(89, 89, 89))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jbuttonAdd1_Consumable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonUpdate1_Consumable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonRemove3_Consumable, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(JButton1_GenReport_Consumable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EquipmentInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EquipmentInfo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consumable Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17), new java.awt.Color(0, 102, 255)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 17))); // NOI18N

        jTable2_Consumable.setFont(jTable2_Consumable.getFont().deriveFont(jTable2_Consumable.getFont().getSize()+10f));
        jTable2_Consumable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Manufacturer", "Size", "Expiration Date", "Location", "Type", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2_Consumable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2_ConsumableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2_Consumable);
        if (jTable2_Consumable.getColumnModel().getColumnCount() > 0) {
            jTable2_Consumable.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable2_Consumable.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel8.setText("Location");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel9.setText("Search Manufacturer");

        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(721, 721, 721))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jTextField7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1869, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane3.addTab("CAIHR MAIN LIST", jPanel21);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1916, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 6, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Laboratory Inventory", jPanel2);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(159, 30));

        jMenuRegister.setText("Create Account");
        jMenuRegister.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jMenuBar1.add(jMenuRegister);

        jMenuAbout.setText("About");
        jMenuAbout.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jMenuBar1.add(jMenuAbout);

        jMenuHelp.setText("Help");
        jMenuHelp.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_SignOutActionPerformed

    private void jbuttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAddActionPerformed
        // TODO add your handling code here:
       
        
       
        try
        {
            ArrayList<JTextField> fields = new ArrayList<>();
            ArrayList<JDateChooser> chooser = new ArrayList<>();
            
            fields.add(jMemoryT);
            fields.add(jHardDriveT);
            fields.add(jManufacturerT);
            fields.add(jModelComputerT);
            fields.add(jServiceTagT);
            fields.add(jUSERSNameT);
            fields.add(jUserIdT);
            fields.add(jUWIAssestTagT);
            fields.add(jHostNameT);
             
            chooser.add(jDateChooserShippedDate);
            chooser.add(jDateChooserWarrantyDate);
            
            
           if(EquipmentManager.checkPanel(fields, chooser))
           {
                Equipment equipment = new Equipment(jManufacturerT.getText(), jModelComputerT.getText(),
                jServiceTagT.getText(), jMemoryT.getText(), jHardDriveT.getText(), 
                jComboBoxLocation.getItemAt(jComboBoxLocation.getSelectedIndex()), 
                DateFormat.getDateInstance().format(jDateChooserShippedDate.getDate()), 
                DateFormat.getDateInstance().format(jDateChooserWarrantyDate.getDate()), jUserIdT.getText(),
                jUSERSNameT.getText(),jUWIAssestTagT.getText(), jHostNameT.getText());
        
           
          
                EquipmentManager.addItem(equipment);
             
            
                JOptionPane.showMessageDialog(null, "Record Successfully Added!");
                EquipmentManager.resetPanel(fields, chooser);
                EquipmentManager.showTable(jTable1);
           }
           else
           {
               JOptionPane.showMessageDialog(null, "All fields are required!");
           }
        
        }
        catch(SQLException e)
        {
            
        }
        catch(HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Unable to Add Record!");
        }
        
        
        //EquipmentManager.test(jManufacturerT.getText(), DateFormat.getDateInstance().format(jDateChooserShippedDate.getDate()));
    }//GEN-LAST:event_jbuttonAddActionPerformed

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
        
        try 
        {
            if((jTextField6.getText()).equals(""))
               jTable1 = EquipmentManager.showTable(jTable1);
            else
               jTable1 = EquipmentManager.checkEquipment(jTextField6.getText(), jTable1);
            
        } 
        catch(SQLException | NullPointerException e) 
        {
            JOptionPane.showMessageDialog(null, "Unable to search for items!");
        }
        
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {
            
             int column = 0;
             int row = jTable1.getSelectedRow();
             String value = jTable1.getModel().getValueAt(row, column).toString();
      
             EquipmentManager.removeEquipment(value);
             EquipmentManager.showTable(jTable1);
             JOptionPane.showMessageDialog(null, "Record deleted!");
             
        }
        
        catch(HeadlessException | SQLException e)
        {
            
        }
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        
        
         try
        {
            int column = 0;
            int row = jTable1.getSelectedRow();
            String value = jTable1.getModel().getValueAt(row, column).toString();
             
            ArrayList<JTextField> fields = new ArrayList<>();
            ArrayList<JDateChooser> chooser = new ArrayList<>();
            
            fields.add(jMemoryT);
            fields.add(jHardDriveT);
            fields.add(jManufacturerT);
            fields.add(jModelComputerT);
            fields.add(jServiceTagT);
            fields.add(jUSERSNameT);
            fields.add(jUserIdT);
            fields.add(jUWIAssestTagT);
            fields.add(jHostNameT);
             
            chooser.add(jDateChooserShippedDate);
            chooser.add(jDateChooserWarrantyDate);
            
            if (EquipmentManager.checkPanel(fields, chooser))
            {
                Equipment equipment = new Equipment(jManufacturerT.getText(), jModelComputerT.getText(),
                jServiceTagT.getText(), jMemoryT.getText(), jHardDriveT.getText(), 
                jComboBoxLocation.getItemAt(jComboBoxLocation.getSelectedIndex()), 
                DateFormat.getDateInstance().format(jDateChooserShippedDate.getDate()), 
                DateFormat.getDateInstance().format(jDateChooserWarrantyDate.getDate()), jUserIdT.getText(),
                jUSERSNameT.getText(),jUWIAssestTagT.getText(), jHostNameT.getText());
                
                EquipmentManager.updateRecord(equipment, value);
                EquipmentManager.showTable(jTable1);
                JOptionPane.showMessageDialog(null, "Update Successful!");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "All fields are required!");
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
       // Get The Index Of The Slected Row 
        int i = jTable1.getSelectedRow();
        int location = 0;

        TableModel model = jTable1.getModel();
        
        switch (model.getValueAt(i,6).toString())
        {
            case "T.M.R.U":
                location = 0;
                break;
            
            case "E.R.U":
                location = 1;
                
            case "S.C.U":
                location = 2;
                
        }
         // Display Slected Row In JTexteFields
        jManufacturerT.setText(model.getValueAt(i,1).toString());
        jModelComputerT.setText(model.getValueAt(i,2).toString());
        jServiceTagT.setText(model.getValueAt(i,3).toString());
        jMemoryT.setText(model.getValueAt(i,4).toString());
        jHardDriveT.setText(model.getValueAt(i,5).toString());
        jComboBoxLocation.setSelectedIndex(location);
        
        
        DateFormat df = new SimpleDateFormat("MMM d, yyyy");
        Date date = null, date2 = null;
       try {
           date = df.parse(model.getValueAt(i, 7).toString());
           date2 = df.parse(model.getValueAt(i, 8).toString());
           
       } catch (ParseException ex) {
           
       }
        
        
        jDateChooserShippedDate.setDate(date);
        jDateChooserWarrantyDate.setDate(date2);
        jUserIdT.setText(model.getValueAt(i, 9).toString());
        jUSERSNameT.setText(model.getValueAt(i, 10).toString());
        jHostNameT.setText(model.getValueAt(i, 12).toString());
        jUWIAssestTagT.setText(model.getValueAt(i, 11).toString());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        try 
        {
            if((jTextField1.getText()).equals(""))
               jTable1 = EquipmentManager.showTable(jTable1);
            else
               jTable1 = EquipmentManager.searchServiceTAG(jTextField1.getText(), jTable1);
            
        } 
        catch(SQLException | NullPointerException e) 
        {
            JOptionPane.showMessageDialog(null, "Unable to search for items!");
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void SignOut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOut1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_SignOut1ActionPerformed

    private void jButtonRemove3_ConsumableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemove3_ConsumableActionPerformed
        // TODO add your handling code here:
        try
        {
            
             int column = 0;
             int row = jTable2_Consumable.getSelectedRow();
             String value = jTable2_Consumable.getModel().getValueAt(row, column).toString();
      
             ConsumableManager.removeConsumable(value);
             ConsumableManager.showTable(jTable2_Consumable);
             JOptionPane.showMessageDialog(null, "Record deleted!");
             
        }
        
        catch(HeadlessException | SQLException e)
        {
            
        }
    }//GEN-LAST:event_jButtonRemove3_ConsumableActionPerformed

    private void jbuttonAdd1_ConsumableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonAdd1_ConsumableActionPerformed
        // TODO add your handling code here:
        
        try
        {
            ArrayList<JTextField> fields = new ArrayList<>();
            ArrayList<JDateChooser> chooser = new ArrayList<>();
            
            fields.add(jNameConsumableT);
            fields.add(jManufacturerConsumableT);
            fields.add(jSizeConsumableT);
            fields.add(jLocationConsumableT);
            fields.add(jTypeConsumableT);
            fields.add(jQuantityConsumableT);
             
            chooser.add(jDateChooserExpDateConsumable);
            
            
           if(ConsumableManager.checkPanel(fields, chooser))
           {
                Consumable consumable = new Consumable(jNameConsumableT.getText(), jManufacturerConsumableT.getText(),
                jSizeConsumableT.getText(), DateFormat.getDateInstance().format(jDateChooserExpDateConsumable.getDate()), 
                jLocationConsumableT.getText(), jTypeConsumableT.getText(), jQuantityConsumableT.getText());
        
           
          
                ConsumableManager.addItem(consumable);
             
            
                JOptionPane.showMessageDialog(null, "Record Successfully Added!");
                ConsumableManager.resetPanel(fields, chooser);
                ConsumableManager.showTable(jTable2_Consumable);
           }
           else
           {
               JOptionPane.showMessageDialog(null, "All fields are required!");
           }
        
        }
        catch(SQLException e)
        {
            
        }
        catch(HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Unable to Add Record!");
        }
        
        
    }//GEN-LAST:event_jbuttonAdd1_ConsumableActionPerformed

    private void jButtonUpdate1_ConsumableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdate1_ConsumableActionPerformed
        // TODO add your handling code here:
          try
        {
            
            int column = 0;
            int row = jTable2_Consumable.getSelectedRow();
            String value = jTable2_Consumable.getModel().getValueAt(row, column).toString();
            
            ArrayList<JTextField> fields = new ArrayList<>();
            ArrayList<JDateChooser> chooser = new ArrayList<>();
            
            fields.add(jNameConsumableT);
            fields.add(jManufacturerConsumableT);
            fields.add(jSizeConsumableT);
            fields.add(jLocationConsumableT);
            fields.add(jTypeConsumableT);
            fields.add(jQuantityConsumableT);
             
            chooser.add(jDateChooserExpDateConsumable);
            
            
           if(ConsumableManager.checkPanel(fields, chooser))
           {
                Consumable consumable = new Consumable(jNameConsumableT.getText(), jManufacturerConsumableT.getText(),
                jSizeConsumableT.getText(), DateFormat.getDateInstance().format(jDateChooserExpDateConsumable.getDate()), 
                jLocationConsumableT.getText(), jTypeConsumableT.getText(), jQuantityConsumableT.getText());
          
                
                ConsumableManager.updateRecord(consumable, value);
                ConsumableManager.showTable(jTable2_Consumable);
                JOptionPane.showMessageDialog(null, "Record Successfully Added!");
           }
           else
           {
               JOptionPane.showMessageDialog(null, "All fields are required!");
           }
        
        }
        catch(SQLException e)
        {
            
        }
        catch(HeadlessException e)
        {
            JOptionPane.showMessageDialog(null, "Unable to Add Record!");
        }
    }//GEN-LAST:event_jButtonUpdate1_ConsumableActionPerformed

    private void jTable2_ConsumableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2_ConsumableMouseClicked
        // TODO add your handling code here:
        // Get The Index Of The Slected Row 
        int i = jTable2_Consumable.getSelectedRow();
        int location = 0;

        TableModel model = jTable2_Consumable.getModel();
        
        switch (model.getValueAt(i,6).toString())
        {
            case "T.M.R.U":
                location = 0;
                break;
            
            case "E.R.U":
                location = 1;
                
            case "S.C.U":
                location = 2;
                
        }
         // Display Slected Row In JTexteFields
        jNameConsumableT.setText(model.getValueAt(i,1).toString());
        jManufacturerConsumableT.setText(model.getValueAt(i,2).toString());
        jSizeConsumableT.setText(model.getValueAt(i,3).toString());
        
        jLocationConsumableT.setText(model.getValueAt(i,5).toString());
        jTypeConsumableT.setText(model.getValueAt(i,6).toString());
        jQuantityConsumableT.setText(model.getValueAt(i, 7).toString());
        
        DateFormat df = new SimpleDateFormat("MMM d, yyyy");
        Date date = null, date2 = null;
       try {
           date = df.parse(model.getValueAt(i,4).toString());
           
       } catch (ParseException ex) {
           
       }
        
        
        jDateChooserExpDateConsumable.setDate(date);
        
    }//GEN-LAST:event_jTable2_ConsumableMouseClicked

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        // TODO add your handling code here:
         try 
        {
            if((jTextField1.getText()).equals(""))
               jTable1 = ConsumableManager.showTable(jTable1);
            else
               jTable1 = ConsumableManager.searchManufacturer(jTextField1.getText(), jTable1);
            
        } 
        catch(SQLException | NullPointerException e) 
        {
            JOptionPane.showMessageDialog(null, "Unable to search for items!");
        }
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jButton1_GenReportEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_GenReportEquipmentActionPerformed
        // TODO add your handling code here:
        new ReportFactory().getReport("Equipment");
        JOptionPane.showMessageDialog(null, "Equipment Report successfully generated!");
    }//GEN-LAST:event_jButton1_GenReportEquipmentActionPerformed

    private void JButton1_GenReport_ConsumableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton1_GenReport_ConsumableActionPerformed
        // TODO add your handling code here:
        new ReportFactory().getReport("Consumable");
        JOptionPane.showMessageDialog(null, "Consumable Report successfully generated!");
    }//GEN-LAST:event_JButton1_GenReport_ConsumableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EquipmentInfo;
    private javax.swing.JPanel EquipmentInfo1;
    private javax.swing.JLabel HardDrive;
    private javax.swing.JLabel HostName;
    private javax.swing.JButton JButton1_GenReport_Consumable;
    private javax.swing.JLabel Location;
    private javax.swing.JLabel LoggedInUser;
    private javax.swing.JLabel LoggedInUser1;
    private javax.swing.JLabel Manufacturer;
    private javax.swing.JLabel Memory;
    private javax.swing.JLabel ModelComputer;
    private javax.swing.JLabel ServiceTag;
    private javax.swing.JLabel ShippedDate;
    private javax.swing.JButton SignOut;
    private javax.swing.JButton SignOut1;
    private javax.swing.JLabel UWIAssetTAG;
    private javax.swing.JLabel UserID;
    private javax.swing.JLabel UsersName;
    private javax.swing.JLabel WarrantyEndDate;
    private javax.swing.JButton jButton1_GenReportEquipment;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonRemove3_Consumable;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JButton jButtonUpdate1_Consumable;
    private javax.swing.JComboBox<String> jComboBoxLocation;
    private com.toedter.calendar.JDateChooser jDateChooserExpDateConsumable;
    private com.toedter.calendar.JDateChooser jDateChooserShippedDate;
    private com.toedter.calendar.JDateChooser jDateChooserWarrantyDate;
    private javax.swing.JLabel jExpDateConsumableL;
    private javax.swing.JTextField jHardDriveT;
    private javax.swing.JTextField jHostNameT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLocationConsumableL;
    private javax.swing.JTextField jLocationConsumableT;
    private javax.swing.JLabel jManufacturerConsumableL;
    private javax.swing.JTextField jManufacturerConsumableT;
    private javax.swing.JTextField jManufacturerT;
    private javax.swing.JTextField jMemoryT;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenu jMenuRegister;
    private javax.swing.JTextField jModelComputerT;
    private javax.swing.JLabel jNameConsumableL;
    private javax.swing.JTextField jNameConsumableT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jQuantityConsumableL;
    private javax.swing.JTextField jQuantityConsumableT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jServiceTagT;
    private javax.swing.JLabel jSizeConsumableL;
    private javax.swing.JTextField jSizeConsumableT;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2_Consumable;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel jTypeConsumableL;
    private javax.swing.JTextField jTypeConsumableT;
    private javax.swing.JTextField jUSERSNameT;
    private javax.swing.JTextField jUWIAssestTagT;
    private javax.swing.JTextField jUserIdT;
    private javax.swing.JButton jbuttonAdd;
    private javax.swing.JButton jbuttonAdd1_Consumable;
    // End of variables declaration//GEN-END:variables
}
